name: Assign Reviewer based on Label

on:
  pull_request:
    types:
      - labeled

permissions:
  contents: write
  pull-requests: write

jobs:
  assign-reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set Reviewer based on Label
        run: |
          declare -A LABELS_TO_REVIEWERS=(
            ["feat"]="nekonado,nekonadocat"
            ["bug"]="nekonado,nekonadocat"
          )

          label="${{ github.event.label.name }}"
          reviewers=${LABELS_TO_REVIEWERS[$label]}

          author_username="${{ github.event.pull_request.user.login }}"

          if [ -n "$reviewers" ]; then
            IFS=',' read -ra reviewers_array <<< "$reviewers"

            filtered_reviewers=()
            for reviewer in "${reviewers_array[@]}"; do
              if [ "$reviewer" != "$author_username" ]; then
                filtered_reviewers+=("$reviewer")
              fi
            done

            if [ ${#filtered_reviewers[@]} -gt 0 ]; then
              reviewers_json=$(printf '%s\n' "${filtered_reviewers[@]}" | jq -c -R 'split("\n") | map(select(length > 0))')

              response=$(curl -s -o /dev/null -w "%{http_code}\n" -X POST \
                -H "Accept: application/vnd.github.v3+json" \
                -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                -H "Content-Type: application/json" \
                "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/requested_reviewers" \
                -d "{\"reviewers\": $reviewers_json}")

              if [ "$response" -ge 200 ] && [ "$response" -lt 300 ]; then
                echo "Reviewers set successfully based on label: $label"
              else
                echo "Failed to set reviewers. HTTP Status Code: $response"
                exit 1
              fi
            else
              echo "No valid reviewers found after filtering."
            fi
          fi
